import { Metadata } from 'next'
import React from 'react';
import Img_upload from '../profile/_components/img_upload';
import Text_Editor from './_components/text_editor';
export const metadata: Metadata = {
    title: 'Next App',
    description: 'Generated by create next app',
  }
export default function Upload(){
    return (
    <>
        <div className='mt-16'>
            <Text_Editor/>
        </div>
    </>
    );
}