import './globals.css'
import './_componenets/css_.css'
import type { Metadata, ResolvingMetadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './_componenets/nav/navbar'
import Footer from './_componenets/nav/footer'
import MsgBox from './_componenets/pop_ups'
const inter = Inter({ subsets: ['latin'] })
//Metadata generation 
type Props = {
  params: { id: string }
  searchParams: { [key: string]: string | string[] | undefined }
}
export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="light" className='h-full selection:bg-accent-focus selection:text-primary' id='body'>
      <script src='../node_modules/tinymce/tinymce.min.js' async></script>
      <body className={`${inter.className} w-full h-full scrollbar-thin scrollbar-track-neutral scrollbar-thumb-primary`}>
        <NavBar />
        <MsgBox />
           {children}
        <Footer />
      </body>
    </html>
  )
}
