import './globals.css'
import './_componenets/css_.css'
import type { Metadata, ResolvingMetadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './_componenets/nav/navbar'
import Footer from './_componenets/nav/footer'
import MsgBox from './_componenets/pop_ups'
const inter = Inter({ subsets: ['latin'] })
//Metadata generation 
type Props = {
  params: { id: string }
  searchParams: { [key: string]: string | string[] | undefined }
}
export const metadata: Metadata = {
  title: 'Z-Blogs',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="light" className='h-full selection:bg-accent-focus selection:text-primary' id='body'>
      <script src='../node_modules/tinymce/tinymce.min.js' async></script>
      <link rel="apple-touch-icon" sizes="114x114" href="./favicons/apple-touch-icon.png" />
      <link rel="icon" type="image/png" sizes="32x32" href="./favicons/favicon-32x32.png" />
      <link rel="icon" type="image/png" sizes="16x16" href="./favicons/favicon-16x16.png" />
      <link rel="mask-icon" href="./favicons/safari-pinned-tab.svg" color="#5bbad5" />
      <meta name="msapplication-TileColor" content="#ffffff" />
      <meta name="theme-color" content="#ffffff"></meta>
      <body className={`${inter.className} w-full h-full scrollbar-thin scrollbar-track-neutral scrollbar-thumb-primary`}>
        <NavBar />
        <MsgBox />
           {children}
        <Footer />
      </body>
    </html>
  )
}
